Обязательная часть

Будем осуществлять работу с непростым набором данных о состоянии здоровья лошадей, испытывающих кишечные колики.

Задание 1. Базовое изучение

Изучить представленный набор данных на основе описания его столбцов и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты.

In [57]:
import pandas as pd
import numpy as np

log = pd.read_csv('hw_15/horse_data.csv', sep = ',', na_values = "?")
log.columns = ['surgery', 'Age', 'Hospital Number','rectal temperature', 'pulse', 'respiratory rate', 'temperature of extremities', 'peripheral pulse', 'mucous_membranes', 'capillary refill time', 'pain', 'peristalsis', 'abdominal_distension', 'nasogastric tube', 'nasogastric reflux', 'nasogastric reflux PH', 'rectal examination', 'abdomen', 'packed cell volume', 'total_protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome', 'surgical lesion', 'site of lesion', 'type of lesion', 'subtype of lesion', 'cp_data']
log.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   surgery                      298 non-null    float64
 1   Age                          299 non-null    int64
 2   Hospital Number              299 non-null    int64
 3   rectal temperature           239 non-null    float64
 4   pulse                        275 non-null    float64
 5   respiratory rate             241 non-null    float64
 6   temperature of extremities   243 non-null    float64
 7   peripheral pulse             230 non-null    float64
 8   mucous_membranes             253 non-null    float64
 9   capillary refill time        267 non-null    float64
 10  pain                         244 non-null    float64
 11  peristalsis                  255 non-null    float64
 12  abdominal_distension         243 non-null    float64
 13  nasogastric tube             196 non-null    float64
 14  nasogastric reflux           194 non-null    float64
 15  nasogastric reflux PH        53 non-null     float64
 16  rectal examination           197 non-null    float64
 17  abdomen                      181 non-null    float64
 18  packed cell volume           270 non-null    float64
 19  total_protein                266 non-null    float64
 20  abdominocentesis appearance  135 non-null    float64
 21  abdomcentesis total protein  102 non-null    float64
 22  outcome                      298 non-null    float64
 23  surgical lesion              299 non-null    int64
 24  site of lesion               299 non-null    int64
 25  type of lesion               299 non-null    int64
 26  subtype of lesion            299 non-null    int64
 27  cp_data                      299 non-null    int64
dtypes: float64(21), int64(7)
memory usage: 65.5 KB

In [2]:
log.head()

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,site of lesion,type of lesion,subtype of lesion,cp_data
0,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
1,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
2,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
3,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
4,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2

1:  surgery?
  
          1 = Yes, it had surgery
          2 = It was treated without surgery
          
2:  Age
   
          1 = Adult horse
          2 = Young (< 6 months)
          
5:  pulse
  
          - linear
          - the heart rate in beats per minute
          - is a reflection of the heart condition: 30 -40 is normal for adults
          - rare to have a lower than normal rate although athletic horses
            may have a rate of 20-25
          - animals with painful lesions or suffering from circulatory shock
            may have an elevated heart rate
            
 9:  mucous membranes
 
          - a subjective measurement of colour
          - possible values are:
               1 = normal pink
               2 = bright pink
               3 = pale pink
               4 = pale cyanotic
               5 = bright red / injected
               6 = dark cyanotic
          - 1 and 2 probably indicate a normal or slightly increased
            circulation
          - 3 may occur in early shock
          - 4 and 6 are indicative of serious circulatory compromise
          - 5 is more indicative of a septicemia
          
11: pain - a subjective judgement of the horse's pain level

          - possible values:
               1 = alert, no pain
               2 = depressed
               3 = intermittent mild pain
               4 = intermittent severe pain
               5 = continuous severe pain
          - should NOT be treated as a ordered or discrete variable!
          - In general, the more painful, the more likely it is to require
            surgery
          - prior treatment of pain may mask the pain level to some extent

13: abdominal distension

          - An IMPORTANT parameter.
          - possible values
               1 = none
               2 = slight
               3 = moderate
               4 = severe
          - an animal with abdominal distension is likely to be painful and
            have reduced gut motility.
          - a horse with severe abdominal distension is likely to require
            surgery just tio relieve the pressure

 20: total protein
 
          - linear
          - normal values lie in the 6-7.5 (gms/dL) range
          - the higher the value the greater the dehydration

23: outcome

          - what eventually happened to the horse?
          - possible values:
               1 = lived
               2 = died
               3 = was euthanized

In [58]:
columns_ = ['Hospital Number','rectal temperature', 'respiratory rate', 'temperature of extremities', 'peripheral pulse', 'capillary refill time', 'peristalsis', 'nasogastric tube', 'nasogastric reflux', 'nasogastric reflux PH', 'rectal examination', 'abdomen', 'packed cell volume', 'abdominocentesis appearance', 'abdomcentesis total protein', 'surgical lesion', 'site of lesion', 'type of lesion', 'subtype of lesion', 'cp_data']
data = log.drop(columns_, 1)
data['Age'] = data['Age'].replace([9],2)
data.head(50)

,surgery,Age,pulse,mucous_membranes,pain,abdominal_distension,total_protein,outcome
0,1.0,1,88.0,4.0,3.0,2.0,85.0,3.0
1,2.0,1,40.0,3.0,3.0,1.0,6.7,1.0
2,1.0,2,164.0,6.0,2.0,4.0,7.2,2.0
3,2.0,1,104.0,6.0,NaN,NaN,7.4,2.0
4,2.0,1,NaN,3.0,2.0,2.0,NaN,1.0
5,1.0,1,48.0,1.0,3.0,3.0,7.0,1.0
6,1.0,1,60.0,NaN,NaN,2.0,8.3,2.0
7,2.0,1,80.0,3.0,4.0,4.0,6.2,3.0
8,2.0,2,90.0,1.0,5.0,1.0,6.2,1.0
9,1.0,1,66.0,5.0,3.0,1.0,6.0,1.0
10,2.0,1,72.0,2.0,2.0,2.0,7.8,1.0
11,1.0,1,42.0,1.0,3.0,3.0,7.0,1.0
12,2.0,2,92.0,2.0,1.0,2.0,6.1,2.0
13,1.0,1,76.0,1.0,3.0,1.0,81.0,1.0
14,1.0,1,96.0,4.0,5.0,3.0,6.8,2.0
15,1.0,2,128.0,4.0,4.0,3.0,7.8,2.0
16,2.0,1,48.0,NaN,NaN,NaN,NaN,1.0
17,1.0,1,64.0,2.0,2.0,1.0,7.0,1.0
18,2.0,1,110.0,6.0,NaN,3.0,8.7,1.0
19,1.0,1,72.0,5.0,5.0,4.0,6.1,1.0
20,2.0,1,48.0,1.0,1.0,1.0,6.8,1.0
21,1.0,1,42.0,4.0,2.0,1.0,7.2,1.0
22,1.0,2,130.0,NaN,2.0,NaN,70.0,1.0
23,1.0,1,60.0,3.0,NaN,3.0,65.0,1.0
24,2.0,1,60.0,NaN,NaN,NaN,NaN,1.0
25,1.0,1,72.0,3.0,3.0,3.0,7.0,1.0
26,1.0,1,48.0,1.0,NaN,2.0,5.5,1.0
27,1.0,1,NaN,NaN,NaN,NaN,NaN,2.0
28,2.0,1,48.0,1.0,1.0,1.0,76.0,1.0
29,2.0,1,96.0,4.0,5.0,4.0,7.5,2.0
30,2.0,1,108.0,4.0,2.0,2.0,8.2,3.0
31,1.0,1,60.0,1.0,3.0,3.0,6.6,1.0
32,1.0,1,64.0,1.0,3.0,NaN,8.6,1.0
33,1.0,1,100.0,4.0,5.0,4.0,6.6,1.0
34,2.0,1,104.0,3.0,4.0,3.0,8.4,3.0
35,2.0,1,112.0,5.0,NaN,1.0,6.0,3.0
36,1.0,1,72.0,NaN,5.0,1.0,80.0,1.0
37,2.0,1,52.0,1.0,3.0,2.0,6.6,1.0
38,1.0,2,146.0,NaN,NaN,NaN,NaN,2.0
39,1.0,1,88.0,6.0,5.0,3.0,6.5,2.0
40,2.0,2,150.0,NaN,NaN,NaN,8.5,1.0
41,2.0,1,60.0,3.0,3.0,1.0,7.0,1.0
42,1.0,1,120.0,4.0,4.0,4.0,67.0,3.0
43,1.0,1,140.0,4.0,4.0,NaN,69.0,3.0
44,2.0,1,120.0,4.0,5.0,4.0,6.5,2.0
45,1.0,1,60.0,4.0,5.0,4.0,7.5,1.0
46,2.0,1,48.0,1.0,1.0,1.0,6.5,1.0
47,1.0,1,80.0,3.0,2.0,3.0,6.5,2.0
48,2.0,1,84.0,5.0,4.0,2.0,5.5,2.0
49,2.0,1,46.0,2.0,1.0,2.0,9.1,1.0

In [4]:
data.info(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   surgery               298 non-null    float64
 1   Age                   299 non-null    int64
 2   pulse                 275 non-null    float64
 3   mucous membranes      253 non-null    float64
 4   pain                  244 non-null    float64
 5   abdominal distension  243 non-null    float64
 6   total protein         266 non-null    float64
 7   outcome               298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.8 KB

In [5]:
print(f'Max возраст: ',max(data.Age))
print(f'Min возраст: ',min(data.Age))
Age_range = data.Age.max() - data.Age.min()
print(f'Размах: ', Age_range)
print(f'Средний возраст: ',np.mean(data.Age))

Max возраст:  2
Min возраст:  1
Размах:  1
Средний возраст:  1.080267558528428

In [6]:
Age_counts = {}
for A in data.Age.round():
    if A not in Age_counts:
        Age_counts[A] = 1
    else:
        Age_counts[A] += 1
        
        
maxA = 0
mode_Age = None
for k, v in Age_counts.items():
    if maxA < v:
        maxA = v
        mode_Age = k
print('Значение моды:', mode_Age, 'количество встречаемости:', maxA)

Значение моды: 1 количество встречаемости: 275

In [7]:
print(f'Медиана: ', data.Age.median())

Медиана:  1.0

In [8]:
print(f'СКО: ', data.Age.std())

СКО:  0.2721624724198464

In [9]:
print(f'Дисперсия: ',data.Age.var())

Дисперсия:  0.07407241139368367

In [10]:
data.describe()

,surgery,Age,pulse,mucous membranes,pain,abdominal distension,total protein,outcome
count,298.000000,299.000000,275.000000,253.000000,244.000000,243.000000,266.000000,298.000000
mean,1.395973,1.080268,71.934545,2.853755,2.942623,2.259259,24.517293,1.550336
std,0.489881,0.272162,28.680522,1.620294,1.303993,1.061472,27.509056,0.737967
min,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,3.300000,1.000000
25%,1.000000,1.000000,48.000000,1.000000,2.000000,1.000000,6.500000,1.000000
50%,1.000000,1.000000,64.000000,3.000000,3.000000,2.000000,7.500000,1.000000
75%,2.000000,1.000000,88.000000,4.000000,4.000000,3.000000,57.000000,2.000000
max,2.000000,2.000000,184.000000,6.000000,5.000000,4.000000,89.000000,3.000000

In [59]:
s1= 0  # had surgery 
s2 = 0 # no surgery

for s in data.surgery:
    if s == 1:
        s1 += 1
    elif s == 2:
        s2 +=1
    else:
        pass

print(f'{round(s1/(s1+s2)*100, 2)}% лошадей перенесли операцию.')

60.4% лошадей перенесли операцию.

Проанализируем, на основе каких факторов можно спрогнозировать летальный исход животного.

In [12]:
data.groupby(['outcome']).median()

,surgery,Age,pulse,mucous membranes,pain,abdominal distension,total protein
outcome,,,,,,,
1.0,1.0,1,54.0,2.0,3.0,2.0,7.5
2.0,1.0,1,86.0,4.0,4.0,3.0,6.8
3.0,1.0,1,82.0,4.0,3.0,3.0,56.0

На основе полученных данных можно предположить, что:
- существует коррекляция между высоким пульсом и летальным исходом (повышенный пульс связан с болезненными поражениями)
- выполнение операции не оказывает заметного влияния на исход
- принятие решения об усыплении лошади могло быть связано с ее сильным обезвоживанием (о чем свидетельствует высокий уровень белка)
- у умерших и усыпленных лошадей слизистые имели бледно-синюшный оттенок, что свидетельствует о серьезном нарушении кровообращения

Задание 2. Работа с выбросами

В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.

In [60]:
q1 = data.Age.quantile(0.25)
q3 = data.Age.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = data[data.Age.between(lower_bound, upper_bound, inclusive=True)].sort_values('Age')
pd.concat([data, remove_outliers]).drop_duplicates(keep=False)

,surgery,Age,pulse,mucous_membranes,pain,abdominal_distension,total_protein,outcome
2,1.0,2,164.0,6.0,2.0,4.0,7.2,2.0
8,2.0,2,90.0,1.0,5.0,1.0,6.2,1.0
12,2.0,2,92.0,2.0,1.0,2.0,6.1,2.0
15,1.0,2,128.0,4.0,4.0,3.0,7.8,2.0
22,1.0,2,130.0,NaN,2.0,NaN,70.0,1.0
38,1.0,2,146.0,NaN,NaN,NaN,NaN,2.0
40,2.0,2,150.0,NaN,NaN,NaN,8.5,1.0
54,1.0,2,160.0,5.0,3.0,4.0,NaN,2.0
73,1.0,2,NaN,NaN,NaN,NaN,4.9,2.0
74,1.0,2,100.0,5.0,2.0,NaN,57.0,3.0
81,1.0,2,100.0,2.0,3.0,1.0,5.7,1.0
102,1.0,2,140.0,1.0,3.0,2.0,5.3,1.0
108,1.0,2,84.0,2.0,3.0,3.0,6.6,2.0
134,1.0,2,136.0,3.0,5.0,3.0,4.9,2.0
190,2.0,2,100.0,1.0,4.0,1.0,4.7,1.0
211,1.0,2,120.0,2.0,3.0,3.0,6.3,1.0
226,1.0,2,NaN,NaN,NaN,NaN,6.5,1.0
228,1.0,2,120.0,NaN,NaN,NaN,54.0,1.0
243,1.0,2,124.0,2.0,2.0,4.0,8.0,1.0
251,1.0,2,124.0,2.0,2.0,4.0,7.6,2.0
254,1.0,2,184.0,1.0,4.0,3.0,3.3,2.0
261,2.0,2,88.0,NaN,NaN,NaN,5.9,1.0
274,1.0,2,150.0,6.0,5.0,2.0,6.2,2.0
286,2.0,2,84.0,NaN,NaN,NaN,5.0,1.0

In [61]:
print(remove_outliers.Age.mean())
print(remove_outliers.Age.median())
print(data.Age.mean() - remove_outliers.Age.mean())
print(data.Age.median() - remove_outliers.Age.median())

1.0
1.0
0.08026755852842804
0.0

Задание 3. Работа с пропусками

Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

In [62]:
for col in data.columns:
    pct_missing = data[col].isna().mean()
    print(f'{col} - {pct_missing :.1%}')

surgery - 0.3%
Age - 0.0%
pulse - 8.0%
mucous_membranes - 15.4%
pain - 18.4%
abdominal_distension - 18.7%
total_protein - 11.0%
outcome - 0.3%

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   surgery               298 non-null    float64
 1   Age                   299 non-null    int64
 2   pulse                 275 non-null    float64
 3   mucous_membranes      253 non-null    float64
 4   pain                  244 non-null    float64
 5   abdominal_distension  243 non-null    float64
 6   total_protein         266 non-null    float64
 7   outcome               298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.8 KB

In [77]:
#print(data.pain.fillna(data.groupby(['pulse', 'mucous membranes']).pain.transform('median')))
data.pain.fillna(data.groupby(['outcome', 'Age']).pain.transform('median'), inplace=True)
data.pulse.fillna(data.groupby(['outcome', 'pain']).pulse.transform('median'), inplace=True)
data.total_protein.fillna(data.groupby(['outcome', 'pain']).total_protein.transform('median'), inplace=True)
data.mucous_membranes.fillna(data.groupby(['pain']).mucous_membranes.transform('median'), inplace=True)
data.abdominal_distension.fillna(data.groupby(['outcome', 'pain']).abdominal_distension.transform('median'), inplace=True)

In [78]:
data.dropna(thresh=1).info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   surgery               298 non-null    float64
 1   Age                   299 non-null    int64
 2   pulse                 299 non-null    float64
 3   mucous_membranes      299 non-null    float64
 4   pain                  299 non-null    float64
 5   abdominal_distension  299 non-null    float64
 6   total_protein         299 non-null    float64
 7   outcome               298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 21.0 KB

In [65]:
for col in data.columns:
    pct_missing = data[col].isna().mean()
    print(f'{col} - {pct_missing :.1%}')

surgery - 0.3%
Age - 0.0%
pulse - 0.0%
mucous_membranes - 4.3%
pain - 0.0%
abdominal_distension - 0.0%
total_protein - 0.0%
outcome - 0.3%

In [45]:
data.head(50)

,surgery,Age,pulse,mucous membranes,pain,abdominal distension,total protein,outcome
0,1.0,1,88.0,4.0,3.00,2.0,85.0,3.0
1,2.0,1,40.0,3.0,3.00,1.0,6.7,1.0
2,1.0,2,164.0,6.0,2.00,4.0,7.2,2.0
3,2.0,1,104.0,6.0,4.00,4.0,7.4,2.0
4,2.0,1,58.0,3.0,2.00,2.0,7.4,1.0
5,1.0,1,48.0,1.0,3.00,3.0,7.0,1.0
6,1.0,1,60.0,1.0,3.00,2.0,8.3,2.0
7,2.0,1,80.0,3.0,4.00,4.0,6.2,3.0
8,2.0,2,90.0,1.0,5.00,1.0,6.2,1.0
9,1.0,1,66.0,5.0,3.00,1.0,6.0,1.0
10,2.0,1,72.0,2.0,2.00,2.0,7.8,1.0
11,1.0,1,42.0,1.0,3.00,3.0,7.0,1.0
12,2.0,2,92.0,2.0,1.00,2.0,6.1,2.0
13,1.0,1,76.0,1.0,3.00,1.0,81.0,1.0
14,1.0,1,96.0,4.0,5.00,3.0,6.8,2.0
15,1.0,2,128.0,4.0,4.00,3.0,7.8,2.0
16,2.0,1,48.0,4.0,4.00,3.0,7.8,1.0
17,1.0,1,64.0,2.0,2.00,1.0,7.0,1.0
18,2.0,1,110.0,6.0,2.00,3.0,8.7,1.0
19,1.0,1,72.0,5.0,5.00,4.0,6.1,1.0
20,2.0,1,48.0,1.0,1.00,1.0,6.8,1.0
21,1.0,1,42.0,4.0,2.00,1.0,7.2,1.0
22,1.0,2,130.0,4.0,2.00,1.0,70.0,1.0
23,1.0,1,60.0,3.0,3.00,3.0,65.0,1.0
24,2.0,1,60.0,3.0,3.00,3.0,65.0,1.0
25,1.0,1,72.0,3.0,3.00,3.0,7.0,1.0
26,1.0,1,48.0,1.0,1.00,2.0,5.5,1.0
27,1.0,1,48.0,1.0,1.00,2.0,5.5,2.0
28,2.0,1,48.0,1.0,1.00,1.0,76.0,1.0
29,2.0,1,96.0,4.0,5.00,4.0,7.5,2.0
30,2.0,1,108.0,4.0,2.00,2.0,8.2,3.0
31,1.0,1,60.0,1.0,3.00,3.0,6.6,1.0
32,1.0,1,64.0,1.0,3.00,3.0,8.6,1.0
33,1.0,1,100.0,4.0,5.00,4.0,6.6,1.0
34,2.0,1,104.0,3.0,4.00,3.0,8.4,3.0
35,2.0,1,112.0,5.0,3.00,1.0,6.0,3.0
36,1.0,1,72.0,5.0,5.00,1.0,80.0,1.0
37,2.0,1,52.0,1.0,3.00,2.0,6.6,1.0
38,1.0,2,146.0,1.0,3.00,2.0,6.6,2.0
39,1.0,1,88.0,6.0,5.00,3.0,6.5,2.0
40,2.0,2,150.0,6.0,2.25,3.0,8.5,1.0
41,2.0,1,60.0,3.0,3.00,1.0,7.0,1.0
42,1.0,1,120.0,4.0,4.00,4.0,67.0,3.0
43,1.0,1,140.0,4.0,4.00,4.0,69.0,3.0
44,2.0,1,120.0,4.0,5.00,4.0,6.5,2.0
45,1.0,1,60.0,4.0,5.00,4.0,7.5,1.0
46,2.0,1,48.0,1.0,1.00,1.0,6.5,1.0
47,1.0,1,80.0,3.0,2.00,3.0,6.5,2.0
48,2.0,1,84.0,5.0,4.00,2.0,5.5,2.0
49,2.0,1,46.0,2.0,1.00,2.0,9.1,1.0